for (i = 1; i <= 12; i++) {
    document.write("1*"+i+"=")
    document.write(i * 1+" ")
    document.write("2*"+i+"=")
    document.write(i * 2+" ")
    document.write("3*"+i+"=")
    document.write(i * 3+" ")
    document.write("4*"+i+"=")
    document.write(i * 4+" ")
    document.write("5*"+i+"=")
    document.write(i * 5+" ")
    document.write("6*"+i+"=")
    document.write(i * 6+" ")
    document.write("7*"+i+"=")
    document.write(i * 7+" ")
    document.write("8*"+i+"=")
    document.write(i * 8+" ")
    document.write("9*"+i+"=")
    document.write(i * 9+" ")
    document.write("10*"+i+"=")
    document.write(i * 10+" ")
    document.write("11*"+i+"=")
    document.write(i * 11+" ")
    document.write("12*"+i+"=")
    document.write(i * 12+" ")
}